# Build linux kernel general dockerfile configuration file
FROM ubuntu:20.04

# define param
ARG PLATFORM="BM1684X" 
ARG LICENSE_BM="10001"
RUN echo "The PLATFORM is: $PLATFORM"
RUN echo "The LICENSE_BM is: ${LICENSE_BM}"

# Add apt sources
RUN cp -a /etc/apt/sources.list /etc/apt/sources.list.bak
RUN sed -i 's|http://.*.ubuntu.com|http://ports.ubuntu.com|g' /etc/apt/sources.list && \
    echo "deb http://ports.ubuntu.com/ubuntu-ports focal main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb http://ports.ubuntu.com/ubuntu-ports focal-security main restricted universe multiverse" >> /etc/apt/sources.list

# Add apt software
ENV DEBIAN_FRONTEND=noninteractive 
ENV TZ=Asia/Shanghai

COPY . .

WORKDIR /workspace/smart-album-tpu

# Install Python 3.10 and set it as default
# Use deadsnakes PPA for Python 3.10 installation
RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common gnupg2 dirmngr && \
    echo "deb http://launchpad.proxy.ustclug.org/deadsnakes/ppa/ubuntu focal main" > /etc/apt/sources.list.d/deadsnakes-ppa.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA6932366A755776 && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3.10 python3.10-dev python3.10-distutils libssl-dev curl && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2 && \
    update-alternatives --set python3 /usr/bin/python3.10 && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3 && \
    apt-get purge -y software-properties-common && \
    pip3 install dfss -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade

RUN ln -sf /usr/local/bin/pip3.10 /usr/bin/pip3.10 && \
    ln -sf /usr/bin/pip3.10 /usr/bin/pip && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3.10 1 && \
    update-alternatives --set pip /usr/bin/pip3.10

RUN apt-get update && apt-get install -y apt-utils \
    && apt-get install -y --on-install-recommends unzip \
    && apt-get install -y --no-install-recommends locales libncurses5 python3-dev python3-pip build-essential gcc g++ \
    && pip3 install -r /workspace/smart-album-tpu/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple 

WORKDIR /workspace/smart-album-tpu

RUN cd /workspace/smart-album-tpu \
    && pyinstaller --onedir --add-data "templates:templates" --add-data "static:static" --add-data "models:models" app.py \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && rm -rf /root/.cache/*

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /workspace/server
ENTRYPOINT ["/bin/bash", "start_run.sh"]